### ISSUE TITLE
parsing go.mod: unexpected module path "github.com/ugorji/go/codec"

### ISSUE THREAD

**Issue by haardikk21** [algorand/go-algorand-sdk#9]
hey,

running macOS Mojave Version 10.14.3 (18D109)

I am using the Go SDK and following the tutorial on the github readme to create a wallet. When I try to run my app, go modules tries to download the package files, and eventually returns an error
```
go: github.com/algorand/go-codec/codec@v0.0.0-20190416102211-17f33432a5ce: parsing go.mod: unexpected module path "github.com/ugorji/go/codec"
go: error loading module requirements
```

**Comment by haardikk21** [comment]
This wasn't an issue when not using go modules

**Comment by jecassis** [comment]
Kind of sad no one from the Algorand dev team has responded for such a long time as they've fix this already in the master branch of their `go-codec` fork. Here is how to use that fix and enable `go modules` for your SDK app:
`go get github.com/algorand/go-codec/codec@master`

[Issue #41](https://github.com/algorand/go-algorand/issues/41) for reference in go-algorand.

**Comment by Vervious** [comment]
Please submit a PR - `go mod` support has not been a priority for the algorand core team

**Comment by jecassis** [comment]
For the SDK, the only change needed is grabbing the correct version of the fork repo as specified above. As a result, I think you can close this issue out.

Regarding `go mod` conversion in `go-algorand` most of the changes you need are already there (specifically the changes needed in the forked repos and some third-party ones). I didn't continue looking at it personally because I saw another community member helping out and the work being mostly completed.

**Comment by Vervious** [comment]
I'll close this issue. Thank you for helping out, there is certainly lots of engineering left to do :)

**Comment by Karmastic** [comment]
This PR #29 should address this issue:
https://github.com/algorand/go-algorand-sdk/pull/29

**Comment by Vervious** [comment]
Thanks @Karmastic!

**Comment by haardikk21** [comment]
Thanks everyone

**Comment by fanyinghao** [comment]
I suffered from it a lot while using go modules feature. Finally, I fork `algorand/go-codec` and use a steady tag version.
